#!/bin/bash
player=mplayer
formats=(mkv mp4 m4a avi ts)
arg=$*

function fork() {
	(setsid "$@" > /dev/null 2>&1 &);
}

function format_in_dir() {
	for ix in ${!formats[*]}
	do
		format=${formats[$ix]}
		if [ "$(find "$arg" -iname "*.$format" | wc -l)" -gt 0 ]
		then
			echo "$format"
			break
		fi
	done
}

function play_media_dir() {
	dir_to_play=$*
	format=$(format_in_dir)

	fork $player "${dir_to_play}/$(ls "$dir_to_play" | grep $format | grep -v sample)"
}

function play_rar_file() {
	file_to_play=$*
	(setsid unrar p -inul "$file_to_play" | mplayer -idx -cache 25000 - > /dev/null 2>&1 &);
}

function play_media_file() {
	file_to_play=$*

	(setsid $player "$file_to_play" > /dev/null 2>&1 &);
}

function get_extension() {
	file=$*
	ext="${file##*.}"

	echo "$ext"
}

function play_file() {
	file_to_play=$*
	ext=$(get_extension "$file_to_play")

	if [ "$ext" == "rar" ]
	then
		play_rar_file "$file_to_play"
	else
		play_media_file "$file_to_play"
	fi
}

function contains_rar_file() {
	path_to_search=$*

	if [ "$(find "$path_to_search" -iname "*.rar" | wc -l)" -gt 0 ]
	then
		echo yes
	fi
}

function contains_part_named_rar_files() {
	path_to_search=$*

	if [ "$(find "$path_to_search" -iname "*part01.rar" | wc -l)" -gt 0 ]
	then
		echo yes
	fi
}

function play_dir() {
	dir_to_play=$*
	dir_contains_rar_file=$(contains_rar_file "$dir_to_play")
	dir_contains_part_named_rar_files=$(contains_part_named_rar_files "$dir_to_play")

	if [ "$dir_contains_rar_file" ]
	then
		file_to_play="*.rar"
		if [ "$dir_contains_part_named_rar_files" ]
		then
			file_to_play="*part01.rar"
		fi
		full_file_to_play="$dir_to_play/$file_to_play"
		play_rar_file "$full_file_to_play"
	else
		play_media_dir "$dir_to_play"
	fi
}

if [ -f "$arg" ] # file
then
	play_file "$arg"
else # directory
	play_dir "$arg"
fi
